# Python Review

Goals :
- recall basic Python vocabulary 
- practice markdown


## Libraries and packages

**Library**: a collection of code that we can use to preform specific tasks in our programs.

**NumPy**:
- core library for numerical computing in Python
- many other libraries use NumPy arrays as building blocks
- computations on NumPy are optimized for speed and memory usage

Lets import NumPy with **standard abreviation**

In [1]:
import numpy as np

## Variables 

**Variables**: a name we assign to a particular object in Python.

Example: 

In [2]:
# Assign a small array to a variable a

a = np.array([[1,2,2],[3,5,8]])

In [3]:
# Run cell with the variable name to show value
a

array([[1, 2, 2],
       [3, 5, 8]])

In [4]:
# Use 'print' function to print the value 

print(a)

[[1 2 2]
 [3 5 8]]


## Objects

**object**: is a bundle of *properties* and *actions* about something specific. 

Example:

Object: data frame

Properties: number rows, names of the columns, date created

Actions: selecting a specific row, adding a new column 

A variable is the name we give a specific object, and the same object can be refrenced by different variables. 

In practice, we. an often use variable and object interchangeably. 


## Types

Every object in Python has a **type**. The type tells us what kind of object it is. 

We can also call the type of an object, the **class** of an object and they both mean what kind of object we have. 


In [5]:
print(a)

# Check the type/class of a variable/object by using `type` function

type(a)

[[1 2 2]
 [3 5 8]]


numpy.ndarray

In [7]:
print(a[0,0])

# Check the type of an entry on the array by indexing 

type(a[0,0])

1


numpy.int64

Notice that `type(a[0,0])` is `numpy.int64` and not just the standard Python integer type. This is telling us that 1 is an integer stored as 64-bit number. 

In [8]:
print(a[1,1]) #row 1 is 0

5


## Functions

`print` was our first example of a Python **function**. 

Functions take in a set of **arguments** and those arguments create an **output**. 

argument = parameter. 

We can ask information about. afunction by executing `?function`

In [9]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**. 

A function has two types of arguments:

- **non-optional arguments**: arguments *you* need to specify for the function to do something
- **optional argument**: arguments that are pre-filled with a default value by the function. You can override them. Optional arguments appear inside the parenthesis in the form `optional_argument = default_value`

In [12]:
print('changing the default end argument', end = ' :)')

changing the default end argument :)

## Attributes & Methods

An object in Python has attributes and methods. 

- **atribute**: a property of an object, some piece of information about it
- **method**: a procedure associated with an obect, an action where the main ingredient is the object. 

### Check-in 

Fish attributes:

- length, color, species
-  die(), bite(), swim()

**Example**

Attributes for `numpy.arrays`

We cna access a variable's attributes and methods by adding a `.` at the end of the variable's name. 

`variable.method()` or `variable.attribute`

In [13]:
a.shape

(2, 3)

In [14]:
type(a.shape)

tuple

In [21]:
# Methods examples

# min() returns the minimum value along a specified axis. 

a.min(axis=0)

array([1, 2, 2])

## Check-in

We can also call the `min` method without any parameters:

In [19]:
a.min()

1

Remember: methods are functions associated with an object. 

In [22]:
type(a.min)

builtin_function_or_method

## Excercse

1. Read the `print` function help. What is the type of the argument `sep`? Is this an optional or non-optional argument? Why?

2. Create two new variables, one with the integer value 77 and another with the string 99.

3. Use your variables to print `77%99%77` by changing the value of one of the optional arguments in `print`.

In [23]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [28]:
# 1. sep is a string inserted between values. Sep is an optional argument with the type 'built-in function'

# sep is the seperating between numbers

In [27]:
#2#2. 

b = 77 #integer
c = '99' #string 

b
c

'99'

In [29]:
print(b,c,b, sep = '%')

77%99%77
